### ISSUE TITLE
Error when unmounting

### ISSUE THREAD

**Issue by jeremyk** [iniamudhan/react-bingmaps#6]
Hi, I am getting an error  again when unmounting and sometimes it starts an infinite loop. Like this:
<img width="679" alt="screen shot 2018-05-02 at 1 42 44 pm" src="https://user-images.githubusercontent.com/223474/39549000-2363125a-4e11-11e8-9e5e-549bf4dbde21.png">

I tried to create a codepen here to repro it:
https://codesandbox.io/s/1oym36pxj3

If you go there and open a console and hide the map, you should see the error.

Thanks again for developing this!

**Comment by iniamudhan** [comment]
@jeremyk I have tried my best to solve this issue. Published as a patch version V-3.3.3. Get latest one and check if issue persists and let me know. Also reopen if it is not fixed. Let me look again. Sorry for late responce.
