### ISSUE TITLE
Getting bounds of map

### ISSUE THREAD

**Issue by jstauffer18914** [iniamudhan/react-bingmaps#8]
TY.   I was wondering if you have any ideas how to get viewable bounds of map I was able to dynamically add info boxes but I can’t find any way to grab ref to component to getBounds.  I need to use this information to search for other locations.  TY

**Comment by iniamudhan** [comment]
@jstauffer18914 get latest version of react-bingmaps from npm and let me know if it satisfies your need. If not, could you get me an example? Thanks

**Comment by jstauffer18914** [comment]
TY this is a great and useful feature!  I think this may give me what i need. (Reference Id and boundary)  I want user to click bing “locate me” button and then show all our custom data points within viewable map.  Thanks again
